name: AWS Configure

on:
    push:
        branches: ["dynamo"]
    pull_request: 
        branches: ["dynamo"]

env:
    AWS_REGION: 'us-east-1'
    AWS_S3_BUCKET_NAME: 'rtconnect-s3'
    S3_BUILD_FILE_PATH: './build'
    # ROLE_NAME: ''

jobs:
    deploy-s3:
        name: Build & Deploy
        runs-on: ubuntu-latest
        # environment: production
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build app
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            
        - name: Install dependencies
          run: npm ci
        - name: Create build file
          run: npm run build

        # #   TEST
        # - name: Configure AWS credentials from Test account
        #   uses: aws-actions/configure-aws-credentials@v4
        #   with:
        #     role-to-assume: arn:aws:iam::111111111111:role/my-github-actions-role-test
        #     aws-region: us-east-1
    
        - name: Configure AWS credentials for Production Account
          uses: aws-actions/configure-aws-credentials@v4
          with:
            # role-to-assume: ${{ env.ROLE_NAME }}
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # context is correct - problem is a github actions glitch - see: https://github.com/github/vscode-github-actions/issues/222
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
            
        - name: Create dynamodb Users table
          run: |
            ../../aws-lambda-gateway/create-table-users.sh